import type {
  Institution,
  Teacher,
  Student,
  Batch,
  MockTest,
  Question,
  Submission,
  SubmissionAnswer,
  Invoice,
  SubscriptionPlan,
  AdminAnalytics,
  TeacherAnalytics,
  StudentAnalytics,
} from "./types";

// ─── Subscription Plans ───────────────────────────────────────────────────────

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    tier: "starter",
    name: "Starter",
    priceMonthly: 1999,
    priceAnnual: 19999,
    maxTeachers: 5,
    maxStudents: 200,
    aiGenerationCredits: 50,
    features: [
      "Up to 200 students",
      "5 faculty accounts",
      "50 AI test generations/month",
      "Instant auto-grading",
      "Basic analytics",
      "Student portal",
    ],
  },
  {
    tier: "institution",
    name: "Institution",
    priceMonthly: 4999,
    priceAnnual: 49999,
    maxTeachers: 25,
    maxStudents: 1000,
    aiGenerationCredits: 999999,
    features: [
      "Up to 1,000 students",
      "25 faculty accounts",
      "Unlimited AI test generation",
      "Deep analytics (question + student level)",
      "Full question bank",
      "Department & permission management",
    ],
  },
  {
    tier: "campus",
    name: "Campus",
    priceMonthly: 9999,
    priceAnnual: 99999,
    maxTeachers: 999999,
    maxStudents: 3000,
    aiGenerationCredits: 999999,
    features: [
      "Up to 3,000 students",
      "Unlimited faculty accounts",
      "Everything in Institution",
      "Priority support",
      "Dedicated onboarding",
      "Admin audit logs",
      "API / ERP export",
    ],
  },
];

// The default tier every new institute lands on at signup — never shown or
// selectable, only assigned automatically by onboardInstitution().
export const FREE_PLAN_LIMITS = {
  maxTeachers: 1,
  maxStudents: 20,
  aiGenerationCredits: 10,
};

// ─── Institutions ─────────────────────────────────────────────────────────────

export const INSTITUTIONS: Institution[] = [
  {
    id: "inst_01",
    name: "Apex Academy",
    domain: "apexacademy.edu",
    adminEmail: "admin@apexacademy.edu",
    primaryColor: "#3B6FFF",
    secondaryColor: "#7C3AED",
    subscriptionTier: "institution",
    maxTeachers: 25,
    maxStudents: 1000,
    createdAt: "2024-01-15T09:00:00Z",
    isActive: true,
    billingStatus: "active",
  },
  {
    id: "inst_02",
    name: "Brilliant Minds Institute",
    domain: "brilliantminds.in",
    adminEmail: "admin@brilliantminds.in",
    primaryColor: "#3B6FFF",
    secondaryColor: "#7C3AED",
    subscriptionTier: "starter",
    maxTeachers: 5,
    maxStudents: 200,
    createdAt: "2024-03-20T11:30:00Z",
    isActive: true,
    billingStatus: "active",
  },
];

// ─── Teachers ─────────────────────────────────────────────────────────────────

export const TEACHERS: Teacher[] = [
  {
    id: "teacher_01",
    institutionId: "inst_01",
    name: "Dr. Ananya Sharma",
    email: "ananya@apexacademy.edu",
    subject: "Mathematics",
    avatarUrl: "",
    isActive: true,
    joinedAt: "2024-02-01T09:00:00Z",
    studentCount: 42,
    testCount: 12,
  },
  {
    id: "teacher_02",
    institutionId: "inst_01",
    name: "Prof. Rahul Verma",
    email: "rahul@apexacademy.edu",
    subject: "Physics",
    avatarUrl: "",
    isActive: true,
    joinedAt: "2024-02-10T09:00:00Z",
    studentCount: 38,
    testCount: 9,
  },
  {
    id: "teacher_03",
    institutionId: "inst_01",
    name: "Ms. Priya Iyer",
    email: "priya@apexacademy.edu",
    subject: "Chemistry",
    avatarUrl: "",
    isActive: false,
    joinedAt: "2024-03-05T09:00:00Z",
    studentCount: 30,
    testCount: 6,
  },
  {
    id: "teacher_04",
    institutionId: "inst_01",
    name: "Mr. Karan Mehta",
    email: "karan@apexacademy.edu",
    subject: "English",
    avatarUrl: "",
    isActive: true,
    joinedAt: "2024-04-01T09:00:00Z",
    studentCount: 55,
    testCount: 15,
  },
];

// ─── Batches ──────────────────────────────────────────────────────────────────

export const BATCHES: Batch[] = [
  {
    id: "batch_01",
    teacherId: "teacher_01",
    institutionId: "inst_01",
    name: "Class 11 - A",
    subject: "Mathematics",
    studentCount: 22,
    createdAt: "2024-02-05T09:00:00Z",
  },
  {
    id: "batch_02",
    teacherId: "teacher_01",
    institutionId: "inst_01",
    name: "Class 12 - B",
    subject: "Mathematics",
    studentCount: 20,
    createdAt: "2024-02-05T09:00:00Z",
  },
  {
    id: "batch_03",
    teacherId: "teacher_02",
    institutionId: "inst_01",
    name: "Class 11 - Physics",
    subject: "Physics",
    studentCount: 38,
    createdAt: "2024-02-15T09:00:00Z",
  },
];

// ─── Students ─────────────────────────────────────────────────────────────────

export const STUDENTS: Student[] = [
  {
    id: "student_01",
    institutionId: "inst_01",
    teacherId: "teacher_01",
    batchId: "batch_01",
    name: "Arjun Patel",
    email: "arjun@student.apexacademy.edu",
    rollNumber: "A11001",
    isActive: true,
    enrolledAt: "2024-02-10T09:00:00Z",
    overallScore: 82,
    testsAttempted: 8,
  },
  {
    id: "student_02",
    institutionId: "inst_01",
    teacherId: "teacher_01",
    batchId: "batch_01",
    name: "Sneha Kapoor",
    email: "sneha@student.apexacademy.edu",
    rollNumber: "A11002",
    isActive: true,
    enrolledAt: "2024-02-10T09:00:00Z",
    overallScore: 91,
    testsAttempted: 8,
  },
  {
    id: "student_03",
    institutionId: "inst_01",
    teacherId: "teacher_01",
    batchId: "batch_01",
    name: "Rohan Das",
    email: "rohan@student.apexacademy.edu",
    rollNumber: "A11003",
    isActive: true,
    enrolledAt: "2024-02-10T09:00:00Z",
    overallScore: 73,
    testsAttempted: 7,
  },
  {
    id: "student_04",
    institutionId: "inst_01",
    teacherId: "teacher_01",
    batchId: "batch_02",
    name: "Meera Joshi",
    email: "meera@student.apexacademy.edu",
    rollNumber: "A12001",
    isActive: true,
    enrolledAt: "2024-02-12T09:00:00Z",
    overallScore: 88,
    testsAttempted: 9,
  },
  {
    id: "student_05",
    institutionId: "inst_01",
    teacherId: "teacher_01",
    batchId: "batch_02",
    name: "Aarav Singh",
    email: "aarav@student.apexacademy.edu",
    rollNumber: "A12002",
    isActive: false,
    enrolledAt: "2024-02-12T09:00:00Z",
    overallScore: 65,
    testsAttempted: 5,
  },
];

// ─── Tests ────────────────────────────────────────────────────────────────────

export const MOCK_TESTS: MockTest[] = [
  {
    id: "test_01",
    teacherId: "teacher_01",
    institutionId: "inst_01",
    batchId: "batch_01",
    title: "Quadratic Equations - Mid Term",
    description: "Covers factoring, discriminant, and applications of quadratic equations.",
    subject: "Mathematics",
    status: "closed",
    totalMarks: 50,
    resultDelayMinutes: 2,
    resultsDeclared: true,
    durationMinutes: 60,
    scheduledAt: "2024-05-10T09:00:00Z",
    closesAt: "2024-05-10T10:00:00Z",
    createdAt: "2024-05-08T14:00:00Z",
    aiGenerated: false,
    attemptCount: 20,
    avgScore: 76,
    questions: [
      {
        id: "q_01",
        testId: "test_01",
        order: 1,
        type: "mcq",
        text: "What is the discriminant of the quadratic equation 2x² - 4x + 2 = 0?",
        marks: 5,
        difficulty: "easy",
        options: [
          { id: "o1", text: "0", isCorrect: true },
          { id: "o2", text: "8", isCorrect: false },
          { id: "o3", text: "-8", isCorrect: false },
          { id: "o4", text: "16", isCorrect: false },
        ],
        explanation: "Discriminant = b² - 4ac = (-4)² - 4(2)(2) = 16 - 16 = 0",
        aiGenerated: false,
      },
      {
        id: "q_02",
        testId: "test_01",
        order: 2,
        type: "mcq",
        text: "Which of the following is a root of x² - 5x + 6 = 0?",
        marks: 5,
        difficulty: "easy",
        options: [
          { id: "o5", text: "1", isCorrect: false },
          { id: "o6", text: "2", isCorrect: true },
          { id: "o7", text: "4", isCorrect: false },
          { id: "o8", text: "7", isCorrect: false },
        ],
        explanation: "Factoring: (x-2)(x-3) = 0, so roots are x=2 and x=3.",
        aiGenerated: false,
      },
      {
        id: "q_03",
        testId: "test_01",
        order: 3,
        type: "true_false",
        text: "A quadratic equation always has two distinct real roots.",
        marks: 5,
        difficulty: "medium",
        options: [
          { id: "o9", text: "True", isCorrect: false },
          { id: "o10", text: "False", isCorrect: true },
        ],
        explanation: "When discriminant < 0, there are no real roots; when discriminant = 0, there is exactly one real root.",
        aiGenerated: false,
      },
      {
        id: "q_04",
        testId: "test_01",
        order: 4,
        type: "text",
        text: "Solve the equation x² - 7x + 12 = 0 and find both roots. Show your working.",
        marks: 10,
        difficulty: "medium",
        correctAnswer: "x = 3 and x = 4 (by factoring: (x-3)(x-4) = 0)",
        aiGenerated: false,
      },
      {
        id: "q_05",
        testId: "test_01",
        order: 5,
        type: "text",
        text: "A ball is thrown upward. Its height h (in meters) after t seconds is given by h = -5t² + 20t + 1. After how many seconds does the ball reach maximum height?",
        marks: 10,
        difficulty: "hard",
        correctAnswer: "t = 2 seconds (vertex at t = -b/2a = -20/(2×-5) = 2)",
        aiGenerated: false,
      },
      {
        id: "q_06",
        testId: "test_01",
        order: 6,
        type: "mcq",
        text: "If both roots of ax² + bx + c = 0 are equal and negative, which condition holds?",
        marks: 5,
        difficulty: "hard",
        options: [
          { id: "o11", text: "b² = 4ac and b/a > 0", isCorrect: true },
          { id: "o12", text: "b² > 4ac and b < 0", isCorrect: false },
          { id: "o13", text: "b² = 4ac and a < 0", isCorrect: false },
          { id: "o14", text: "b² < 4ac and a > 0", isCorrect: false },
        ],
        explanation: "Equal roots require b²=4ac. Both negative means sum of roots = -b/a < 0, so b/a > 0.",
        aiGenerated: false,
      },
      {
        id: "q_07",
        testId: "test_01",
        order: 7,
        type: "text",
        text: "Briefly explain the relationship between the discriminant and the nature of roots of a quadratic equation.",
        marks: 10,
        difficulty: "medium",
        correctAnswer: "If D > 0: two distinct real roots; D = 0: one repeated real root; D < 0: two complex (imaginary) roots.",
        aiGenerated: false,
      },
    ],
  },
  {
    id: "test_02",
    teacherId: "teacher_01",
    institutionId: "inst_01",
    batchId: "batch_01",
    title: "Calculus Fundamentals - AI Generated",
    description: "AI-generated test on differentiation and integration basics.",
    subject: "Mathematics",
    status: "published",
    totalMarks: 40,
    durationMinutes: 45,
    resultDelayMinutes: 2,
    resultsDeclared: false,
    scheduledAt: "2026-07-01T10:00:00Z",
    closesAt: "2026-07-01T10:45:00Z",
    createdAt: "2024-06-01T09:00:00Z",
    aiGenerated: true,
    attemptCount: 0,
    avgScore: 0,
    questions: [
      {
        id: "q_ai_01",
        testId: "test_02",
        order: 1,
        type: "mcq",
        text: "What is the derivative of f(x) = 3x⁴ - 2x² + 5?",
        marks: 5,
        difficulty: "easy",
        options: [
          { id: "ai_o1", text: "12x³ - 4x", isCorrect: true },
          { id: "ai_o2", text: "12x³ - 2x", isCorrect: false },
          { id: "ai_o3", text: "3x³ - 4x", isCorrect: false },
          { id: "ai_o4", text: "12x⁴ - 4x²", isCorrect: false },
        ],
        explanation: "Using power rule: d/dx[3x⁴] = 12x³ and d/dx[-2x²] = -4x. Constant 5 differentiates to 0.",
        aiGenerated: true,
      },
      {
        id: "q_ai_02",
        testId: "test_02",
        order: 2,
        type: "mcq",
        text: "∫(2x + 3)dx = ?",
        marks: 5,
        difficulty: "easy",
        options: [
          { id: "ai_o5", text: "x² + 3x + C", isCorrect: true },
          { id: "ai_o6", text: "2x² + 3x + C", isCorrect: false },
          { id: "ai_o7", text: "x² + C", isCorrect: false },
          { id: "ai_o8", text: "2 + C", isCorrect: false },
        ],
        explanation: "∫2x dx = x², ∫3 dx = 3x. Add constant C.",
        aiGenerated: true,
      },
      {
        id: "q_ai_03",
        testId: "test_02",
        order: 3,
        type: "true_false",
        text: "The derivative of a constant function is always 1.",
        marks: 5,
        difficulty: "easy",
        options: [
          { id: "ai_o9", text: "True", isCorrect: false },
          { id: "ai_o10", text: "False", isCorrect: true },
        ],
        explanation: "The derivative of any constant c is 0, not 1.",
        aiGenerated: true,
      },
      {
        id: "q_ai_04",
        testId: "test_02",
        order: 4,
        type: "text",
        text: "Find the critical points of f(x) = x³ - 3x² + 2 and determine if they are maxima or minima.",
        marks: 10,
        difficulty: "hard",
        correctAnswer: "f'(x) = 3x² - 6x = 3x(x-2) = 0. Critical points: x=0 (local max), x=2 (local min).",
        aiGenerated: true,
      },
      {
        id: "q_ai_05",
        testId: "test_02",
        order: 5,
        type: "mcq",
        text: "What does the second derivative test tell us about a critical point where f''(x) > 0?",
        marks: 5,
        difficulty: "medium",
        options: [
          { id: "ai_o11", text: "Local minimum", isCorrect: true },
          { id: "ai_o12", text: "Local maximum", isCorrect: false },
          { id: "ai_o13", text: "Inflection point", isCorrect: false },
          { id: "ai_o14", text: "Cannot be determined", isCorrect: false },
        ],
        explanation: "When f''(x) > 0, the curve is concave up at that point, indicating a local minimum.",
        aiGenerated: true,
      },
      {
        id: "q_ai_06",
        testId: "test_02",
        order: 6,
        type: "text",
        text: "Evaluate ∫₀² (x² + 1) dx. Show all steps.",
        marks: 10,
        difficulty: "medium",
        correctAnswer: "[x³/3 + x]₀² = (8/3 + 2) - 0 = 14/3 ≈ 4.67",
        aiGenerated: true,
      },
    ],
  },
  {
    id: "test_03",
    teacherId: "teacher_01",
    institutionId: "inst_01",
    batchId: "batch_01",
    title: "Trigonometry Basics",
    description: "Draft test on trigonometric identities and functions.",
    subject: "Mathematics",
    status: "draft",
    totalMarks: 30,
    durationMinutes: 30,
    resultDelayMinutes: 2,
    resultsDeclared: false,
    createdAt: "2024-06-15T11:00:00Z",
    aiGenerated: false,
    attemptCount: 0,
    avgScore: 0,
    questions: [],
  },
];

// ─── Submissions ──────────────────────────────────────────────────────────────

export const SUBMISSIONS: Submission[] = [
  {
    id: "sub_01",
    testId: "test_01",
    studentId: "student_01",
    studentName: "Arjun Patel",
    status: "graded",
    startedAt: "2024-05-10T09:02:00Z",
    submittedAt: "2024-05-10T09:54:00Z",
    gradedAt: "2024-05-11T14:00:00Z",
    totalScore: 38,
    maxScore: 50,
    percentage: 76,
    timeTakenMinutes: 52,
    answers: [
      { questionId: "q_01", selectedOptionId: "o1", isCorrect: true, marksAwarded: 5, timeSpentSeconds: 45 },
      { questionId: "q_02", selectedOptionId: "o6", isCorrect: true, marksAwarded: 5, timeSpentSeconds: 60 },
      { questionId: "q_03", selectedOptionId: "o9", isCorrect: false, marksAwarded: 0, timeSpentSeconds: 30 },
      { questionId: "q_04", textAnswer: "x = 3 and x = 4", isCorrect: true, marksAwarded: 9, teacherFeedback: "Good working but show all factoring steps clearly.", timeSpentSeconds: 420 },
      { questionId: "q_05", textAnswer: "t = 2 seconds", isCorrect: true, marksAwarded: 9, teacherFeedback: "Excellent! Well explained.", timeSpentSeconds: 480 },
      { questionId: "q_06", selectedOptionId: "o11", isCorrect: true, marksAwarded: 5, timeSpentSeconds: 90 },
      { questionId: "q_07", textAnswer: "When D > 0 two real roots, D = 0 one root, D < 0 no real roots.", isCorrect: true, marksAwarded: 5, teacherFeedback: "Partially correct. Mention D < 0 gives complex roots.", timeSpentSeconds: 300 },
    ],
  },
  {
    id: "sub_02",
    testId: "test_01",
    studentId: "student_02",
    studentName: "Sneha Kapoor",
    status: "graded",
    startedAt: "2024-05-10T09:01:00Z",
    submittedAt: "2024-05-10T09:48:00Z",
    gradedAt: "2024-05-11T14:30:00Z",
    totalScore: 46,
    maxScore: 50,
    percentage: 92,
    timeTakenMinutes: 47,
    answers: [
      { questionId: "q_01", selectedOptionId: "o1", isCorrect: true, marksAwarded: 5, timeSpentSeconds: 30 },
      { questionId: "q_02", selectedOptionId: "o6", isCorrect: true, marksAwarded: 5, timeSpentSeconds: 40 },
      { questionId: "q_03", selectedOptionId: "o10", isCorrect: true, marksAwarded: 5, timeSpentSeconds: 25 },
      { questionId: "q_04", textAnswer: "(x-3)(x-4)=0, so x=3 and x=4", isCorrect: true, marksAwarded: 10, teacherFeedback: "Perfect!", timeSpentSeconds: 360 },
      { questionId: "q_05", textAnswer: "Maximum at t = -20 / (2×-5) = 2 seconds", isCorrect: true, marksAwarded: 10, teacherFeedback: "Excellent formula application.", timeSpentSeconds: 400 },
      { questionId: "q_06", selectedOptionId: "o11", isCorrect: true, marksAwarded: 5, timeSpentSeconds: 120 },
      { questionId: "q_07", textAnswer: "D > 0: two distinct real roots; D = 0: one repeated real root; D < 0: two complex conjugate roots", isCorrect: true, marksAwarded: 6, teacherFeedback: "Excellent explanation!", timeSpentSeconds: 280 },
    ],
  },
  {
    id: "sub_03",
    testId: "test_01",
    studentId: "student_03",
    studentName: "Rohan Das",
    status: "submitted",
    startedAt: "2024-05-10T09:05:00Z",
    submittedAt: "2024-05-10T09:58:00Z",
    gradedAt: undefined,
    totalScore: 0,
    maxScore: 50,
    percentage: 0,
    timeTakenMinutes: 53,
    answers: [
      { questionId: "q_01", selectedOptionId: "o2", isCorrect: false, timeSpentSeconds: 60 },
      { questionId: "q_02", selectedOptionId: "o6", isCorrect: true, timeSpentSeconds: 50 },
      { questionId: "q_03", selectedOptionId: "o10", isCorrect: true, timeSpentSeconds: 30 },
      { questionId: "q_04", textAnswer: "I think the answer is x = 3 and x = 4 by trial and error.", timeSpentSeconds: 380 },
      { questionId: "q_05", textAnswer: "The ball reaches max at t = 2 seconds", timeSpentSeconds: 450 },
      { questionId: "q_06", selectedOptionId: "o12", isCorrect: false, timeSpentSeconds: 100 },
      { questionId: "q_07", textAnswer: "The discriminant tells us about roots. If positive, two roots. If zero, one root.", timeSpentSeconds: 260 },
    ],
  },
];

// ─── Invoices ─────────────────────────────────────────────────────────────────

export const INVOICES: Invoice[] = [
  {
    id: "inv_001",
    institutionId: "inst_01",
    amount: 79,
    currency: "USD",
    status: "paid",
    issuedAt: "2024-05-01T00:00:00Z",
    dueAt: "2024-05-15T00:00:00Z",
    paidAt: "2024-05-05T00:00:00Z",
    description: "Growth Plan - May 2024",
  },
  {
    id: "inv_002",
    institutionId: "inst_01",
    amount: 79,
    currency: "USD",
    status: "paid",
    issuedAt: "2024-06-01T00:00:00Z",
    dueAt: "2024-06-15T00:00:00Z",
    paidAt: "2024-06-03T00:00:00Z",
    description: "Growth Plan - June 2024",
  },
  {
    id: "inv_003",
    institutionId: "inst_01",
    amount: 79,
    currency: "USD",
    status: "pending",
    issuedAt: "2024-07-01T00:00:00Z",
    dueAt: "2024-07-15T00:00:00Z",
    description: "Growth Plan - July 2024",
  },
];

// ─── Analytics ────────────────────────────────────────────────────────────────

export const ADMIN_ANALYTICS: AdminAnalytics = {
  institutionId: "inst_01",
  totalTeachers: 4,
  activeTeachers: 3,
  totalStudents: 165,
  activeStudents: 148,
  totalTestsCreated: 27,
  testsThisMonth: 6,
  avgInstitutionScore: 78,
  aiGenerationsUsed: 34,
  aiGenerationsLimit: 100,
  teachersTrend: 0,
  studentsTrend: 0,
  testsTrend: 0,
};

export const TEACHER_ANALYTICS: TeacherAnalytics = {
  teacherId: "teacher_01",
  totalStudents: 42,
  totalTestsCreated: 12,
  totalSubmissions: 89,
  pendingGrading: 3,
  avgClassScore: 79,
  topPerformer: "Sneha Kapoor",
  recentTestScores: [
    { testTitle: "Quadratic Equations", avgScore: 76, date: "2024-05-10" },
    { testTitle: "Linear Functions", avgScore: 82, date: "2024-04-18" },
    { testTitle: "Sets & Relations", avgScore: 71, date: "2024-04-01" },
    { testTitle: "Probability Basics", avgScore: 84, date: "2024-03-20" },
    { testTitle: "Matrices", avgScore: 68, date: "2024-03-05" },
  ],
};

export const STUDENT_ANALYTICS: StudentAnalytics = {
  studentId: "student_01",
  overallScore: 82,
  testsAttempted: 8,
  testsPassed: 7,
  avgTimePerTest: 48,
  bestSubject: "Mathematics",
  weakSubject: "Trigonometry",
  scoreHistory: [
    { testTitle: "Quadratic Equations", score: 38, maxScore: 50, date: "2024-05-10" },
    { testTitle: "Linear Functions", score: 42, maxScore: 50, date: "2024-04-18" },
    { testTitle: "Sets & Relations", score: 36, maxScore: 50, date: "2024-04-01" },
    { testTitle: "Probability Basics", score: 44, maxScore: 50, date: "2024-03-20" },
    { testTitle: "Matrices", score: 30, maxScore: 50, date: "2024-03-05" },
    { testTitle: "Coordinate Geometry", score: 40, maxScore: 50, date: "2024-02-20" },
    { testTitle: "Number Theory", score: 38, maxScore: 50, date: "2024-02-05" },
    { testTitle: "Arithmetic Progressions", score: 45, maxScore: 50, date: "2024-01-25" },
  ],
  subjectBreakdown: [
    { subject: "Algebra", avgScore: 84 },
    { subject: "Calculus", avgScore: 78 },
    { subject: "Trigonometry", avgScore: 72 },
    { subject: "Statistics", avgScore: 88 },
    { subject: "Geometry", avgScore: 80 },
  ],
};

// ─── AI Generated Test Templates ──────────────────────────────────────────────

export const AI_TEST_TEMPLATE: Omit<MockTest, "id" | "createdAt" | "teacherId" | "institutionId" | "batchId"> = {
  title: "Derivatives & Limits – AI Generated",
  description: "Comprehensive test on limits, continuity, and derivatives generated by Facultify AI.",
  subject: "Mathematics",
  status: "draft",
  totalMarks: 50,
  durationMinutes: 60,
  resultDelayMinutes: 2,
  resultsDeclared: false,
  aiGenerated: true,
  attemptCount: 0,
  avgScore: 0,
  questions: [
    {
      id: "ai_gen_q1",
      testId: "ai_gen",
      order: 1,
      type: "mcq",
      text: "What is lim(x→0) sin(x)/x?",
      marks: 5,
      difficulty: "easy",
      options: [
        { id: "ag1", text: "0", isCorrect: false },
        { id: "ag2", text: "1", isCorrect: true },
        { id: "ag3", text: "∞", isCorrect: false },
        { id: "ag4", text: "Undefined", isCorrect: false },
      ],
      explanation: "This is the standard limit. As x approaches 0, sin(x)/x approaches 1.",
      aiGenerated: true,
    },
    {
      id: "ai_gen_q2",
      testId: "ai_gen",
      order: 2,
      type: "mcq",
      text: "If f(x) = eˣ, then f'(x) is:",
      marks: 5,
      difficulty: "easy",
      options: [
        { id: "ag5", text: "eˣ", isCorrect: true },
        { id: "ag6", text: "xeˣ⁻¹", isCorrect: false },
        { id: "ag7", text: "ln(x)", isCorrect: false },
        { id: "ag8", text: "1/eˣ", isCorrect: false },
      ],
      explanation: "The derivative of eˣ is eˣ — it is its own derivative.",
      aiGenerated: true,
    },
    {
      id: "ai_gen_q3",
      testId: "ai_gen",
      order: 3,
      type: "true_false",
      text: "Every differentiable function is also continuous.",
      marks: 5,
      difficulty: "medium",
      options: [
        { id: "ag9", text: "True", isCorrect: true },
        { id: "ag10", text: "False", isCorrect: false },
      ],
      explanation: "Differentiability implies continuity, but not vice versa.",
      aiGenerated: true,
    },
    {
      id: "ai_gen_q4",
      testId: "ai_gen",
      order: 4,
      type: "mcq",
      text: "The derivative of ln(x) is:",
      marks: 5,
      difficulty: "easy",
      options: [
        { id: "ag11", text: "1/x", isCorrect: true },
        { id: "ag12", text: "x", isCorrect: false },
        { id: "ag13", text: "eˣ", isCorrect: false },
        { id: "ag14", text: "ln(x)/x", isCorrect: false },
      ],
      explanation: "d/dx[ln(x)] = 1/x for x > 0.",
      aiGenerated: true,
    },
    {
      id: "ai_gen_q5",
      testId: "ai_gen",
      order: 5,
      type: "text",
      text: "Using the chain rule, differentiate f(x) = sin(3x² + 1). Show all steps.",
      marks: 10,
      difficulty: "medium",
      correctAnswer: "f'(x) = cos(3x² + 1) · 6x = 6x·cos(3x² + 1)",
      aiGenerated: true,
    },
    {
      id: "ai_gen_q6",
      testId: "ai_gen",
      order: 6,
      type: "text",
      text: "Evaluate lim(x→2) (x² - 4)/(x - 2). Explain your approach.",
      marks: 10,
      difficulty: "medium",
      correctAnswer: "Factor: (x+2)(x-2)/(x-2) = x+2. At x=2: 2+2 = 4.",
      aiGenerated: true,
    },
    {
      id: "ai_gen_q7",
      testId: "ai_gen",
      order: 7,
      type: "mcq",
      text: "What is the derivative of f(x) = x² · sin(x)?",
      marks: 10,
      difficulty: "hard",
      options: [
        { id: "ag15", text: "2x·sin(x) + x²·cos(x)", isCorrect: true },
        { id: "ag16", text: "2x·cos(x)", isCorrect: false },
        { id: "ag17", text: "x²·cos(x)", isCorrect: false },
        { id: "ag18", text: "2x·sin(x) - x²·cos(x)", isCorrect: false },
      ],
      explanation: "Product rule: d/dx[u·v] = u'v + uv'. u=x², u'=2x; v=sin(x), v'=cos(x).",
      aiGenerated: true,
    },
  ],
};
